# Generated by Django 5.0.6 on 2024-06-02 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=128)),
                ('usertag', models.CharField(max_length=128)),
                ('balance', models.IntegerField(default=5000)),
                ('gpc', models.IntegerField(default=2)),
                ('max_taps', models.IntegerField(default=2000)),
                ('current_taps', models.IntegerField(default=0)),
                ('lvl', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.IntegerField()),
                ('comp_lvl', models.IntegerField(default=1)),
                ('webcam_lvl', models.IntegerField(default=1)),
                ('micro_lvl', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.telegramuser')),
            ],
        ),
    ]
