# Generated by Django 5.0.6 on 2024-07-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='current_taps',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='max_taps',
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
