# Generated by Django 5.0.6 on 2024-07-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_telegramuser_current_taps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='gpc',
        ),
    ]
