# Generated by Django 5.0.6 on 2024-07-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_telegramuser_gpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='energy',
            field=models.IntegerField(default=2000),
        ),
    ]
