# Generated by Django 5.0.6 on 2024-07-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_telegramuser_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='gold_per_hour',
            field=models.FloatField(default=6.25),
        ),
    ]
