# Generated by Django 5.0.6 on 2024-07-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_telegramuser_gold_per_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='gold_per_hour',
            new_name='gph',
        ),
    ]
