# Generated by Django 5.0.6 on 2024-07-27 23:18

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_telegramuser_gpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='mining_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='mining_end',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
