# Generated by Django 5.0.6 on 2024-07-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_telegramuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
