# Generated by Django 5.0.6 on 2024-07-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_telegramuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='max_energy',
            field=models.IntegerField(default=2000),
        ),
    ]
