# Generated by Django 5.0.6 on 2024-07-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_telegramuser_video_lvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='modifier',
            field=models.FloatField(default=1),
        ),
    ]
