# Generated by Django 5.0.6 on 2024-08-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_telegramuser_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='subscribe_money_gived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
