# Generated by Django 5.0.6 on 2024-08-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_referal'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='ispremium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
