# Generated by Django 5.0.6 on 2024-08-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_telegramuser_ispremium_telegramuser_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='friends_invited',
            field=models.IntegerField(default=0),
        ),
    ]
