# Generated by Django 5.0.6 on 2024-08-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_telegramuser_daily_reward_claimed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='secs_in_game',
            field=models.IntegerField(default=0),
        ),
    ]
