# Generated by Django 5.0.6 on 2024-08-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_task_alter_telegramuser_gph_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='group_link',
            new_name='site_link',
        ),
    ]
