# Generated by Django 5.0.6 on 2024-08-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_telegramuser_mining_time_lvl_alter_task_channel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='sound',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='vibrate',
            field=models.BooleanField(default=True),
        ),
    ]
