# Generated by Django 5.0.6 on 2024-08-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_telegramuser_sound_telegramuser_vibrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
