# Generated by Django 5.0.6 on 2024-08-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_telegramuser_video2_lvl_telegramuser_video3_lvl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments_cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video2', models.IntegerField(default=150)),
                ('video3', models.IntegerField(default=150)),
                ('video4', models.IntegerField(default=150)),
                ('mining_duration6', models.IntegerField(default=100)),
                ('mining_duration7', models.IntegerField(default=100)),
                ('mining_duration8', models.IntegerField(default=100)),
                ('mining_duration9', models.IntegerField(default=100)),
                ('mining_duration10', models.IntegerField(default=100)),
            ],
        ),
    ]
