# Generated by Django 5.0.1 on 2024-08-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_payments_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='energy',
            field=models.IntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='max_energy',
            field=models.IntegerField(default=250),
        ),
    ]
